GET http://localhost:3000

###

GET http://localhost:3000/categories

###

GET http://localhost:3000/categories/1

###

GET http://localhost:3000/categories/9999

###

POST http://localhost:3000/categories
Content-Type: application/json

{
  "name": "Category Supertest",
  "description": "Movie category which is named \"Supertest\""
}

###

PATCH http://localhost:3000/categories/1
Content-Type: application/json

{
  "name": "Category Supertest",
  "description": "Movie category which is named \"Supertest\""
}
