GET http://localhost:3000

###

GET http://localhost:3000/categories

###

GET http://localhost:3000/categories/1

###

GET http://localhost:3000/categories/9999

###

POST http://localhost:3000/categories
Content-Type: application/json

{
  "name": "Supertest",
  "description": "Generic movie category"
}

###

PATCH http://localhost:3000/categories/3
Content-Type: application/json

{
  "description": "Movie category which is named \"Supertest\""
}

###

DELETE http://localhost:3000/categories/3
